require("base")
require("maps")
require("color")
require("plugins")
require("lsp")
-- require("p-cmp")
require("p-kind")
-- require("p-snip")
require("p-tree")
require("p-telescope")
require("colorizer")
require('comment')
require('line')
